name: gr
version: '0.1.0.0'
synopsis: Initial project template from stack
description: Please see README.md
category: Web
author: Author name here
maintainer: example@example.com
copyright: 2016 Author name here
license: BSD3
github: jmn/gr
executables:
  gr:
    main: ../app/Main.hs
    source-dirs:
    - src
    - app
    dependencies:
    - base >=4.7 && <5
    - text
    - xml-lens
    - xml-conduit
    - http-client-tls
    - http-client
    - HTTP
    - url
    - http-types
    - http-conduit
    - authenticate-oauth
    - optparse-applicative
    - utf8-string
    - containers
    - bytestring
    - case-insensitive
    - safe-exceptions
    - containers
    - app-settings
    - lens
    - double-conversion
    - formatting
    - haskeline
    - pandoc
tests:
  g-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
